# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
#
name: E5_Renewal

on:
  schedule:
    - cron: '0 0/8 * * *'
  release:
    types: [published]
  watch:
    types: [started]

jobs: 
  Call-APi:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id # 自己star启动
    steps:
    - name: Setup timezone
      uses: zcong1993/setup-timezone@v1.1.1
      with:
        timezone: Asia/Shanghai
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run jar
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        TENANT_GUID: ${{ secrets.TENANT_GUID }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        CLIENT_ID2: ${{ secrets.CLIENT_ID2 }}
        CLIENT_SECRET2: ${{ secrets.CLIENT_SECRET2 }}
        TENANT_GUID2: ${{ secrets.TENANT_GUID2 }}
        USERNAME2: ${{ secrets.USERNAME2 }}
        PASSWORD2: ${{ secrets.PASSWORD2 }}
      run: |
        java -jar ./e5_renewal.jar "$CLIENT_ID" "$USERNAME" "$PASSWORD" "$TENANT_GUID" "$CLIENT_SECRET"  > ./run.log
        java -jar ./e5_renewal.jar "$CLIENT_ID2" "$USERNAME2" "$PASSWORD2" "$TENANT_GUID2" "$CLIENT_SECRET2"  >> ./run.log
        tail run.log

    - name: Telegram notice
      env:
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
      run: |
        curl -X POST "https://api.telegram.org/bot$TG_BOT_TOKEN/sendMessage" -d "chat_id=$TG_USER_ID&text=E5_renewal运行结果通知
        `cat ./run.log`"

    - name: Commit log
      env:
        NAME: fqdata123
        EMAIL: ${{ secrets.GithubEmail }}
      run: |
        git config --global user.name "$NAME"
        git config --global user.email "$EMAIL"
        git add .
        git commit -m "update log" -a
    - name: Push log
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
        branch: main
